//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zegogo.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zegogo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a photo.
        /// </summary>
        internal static string add_photo {
            get {
                return ResourceManager.GetString("add photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All categories.
        /// </summary>
        internal static string all_cat {
            get {
                return ResourceManager.GetString("all cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All in category:.
        /// </summary>
        internal static string all_in_cat {
            get {
                return ResourceManager.GetString("all in cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OTHER ANNOUNCEMENTS BY THE AUTHOR.
        /// </summary>
        internal static string another_adv {
            get {
                return ResourceManager.GetString("another adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application language.
        /// </summary>
        internal static string app_lang {
            get {
                return ResourceManager.GetString("app lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Archival.
        /// </summary>
        internal static string arch {
            get {
                return ResourceManager.GetString("arch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure?.
        /// </summary>
        internal static string are_u_sure {
            get {
                return ResourceManager.GetString("are u sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string auth {
            get {
                return ResourceManager.GetString("auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Before:.
        /// </summary>
        internal static string before {
            get {
                return ResourceManager.GetString("before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BUSINESS.
        /// </summary>
        internal static string BUSINESS {
            get {
                return ResourceManager.GetString("BUSINESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To call.
        /// </summary>
        internal static string call {
            get {
                return ResourceManager.GetString("call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Password.
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose category.
        /// </summary>
        internal static string choose_cat {
            get {
                return ResourceManager.GetString("choose cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на City, country.
        /// </summary>
        internal static string city_country {
            get {
                return ResourceManager.GetString("city country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correspondence on your ads and answers from other users will be displayed here..
        /// </summary>
        internal static string correspondence_on_your_ads {
            get {
                return ResourceManager.GetString("correspondence on your ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 days lift.
        /// </summary>
        internal static string days_lift_7 {
            get {
                return ResourceManager.GetString("days lift 7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 30 days standard ad.
        /// </summary>
        internal static string days_standard_ad_30 {
            get {
                return ResourceManager.GetString("days standard ad 30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 days VIP ad.
        /// </summary>
        internal static string days_VIP_ad_7 {
            get {
                return ResourceManager.GetString("days VIP ad 7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exchange.
        /// </summary>
        internal static string exchange {
            get {
                return ResourceManager.GetString("exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Featured.
        /// </summary>
        internal static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        internal static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Is free.
        /// </summary>
        internal static string free {
            get {
                return ResourceManager.GetString("free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From:.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Headline.
        /// </summary>
        internal static string headline {
            get {
                return ResourceManager.GetString("headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I agree with .
        /// </summary>
        internal static string I_agree_with {
            get {
                return ResourceManager.GetString("I agree with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IN ADDITION TO PACKAGES.
        /// </summary>
        internal static string In_addition_to_packages {
            get {
                return ResourceManager.GetString("In addition to packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lemmikutes:.
        /// </summary>
        internal static string in_fav {
            get {
                return ResourceManager.GetString("in fav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load more....
        /// </summary>
        internal static string load_more {
            get {
                return ResourceManager.GetString("load more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log out.
        /// </summary>
        internal static string log_out {
            get {
                return ResourceManager.GetString("log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messages.
        /// </summary>
        internal static string messages {
            get {
                return ResourceManager.GetString("messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My announcements.
        /// </summary>
        internal static string my_announcements {
            get {
                return ResourceManager.GetString("my announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My profile.
        /// </summary>
        internal static string my_profile {
            get {
                return ResourceManager.GetString("my profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My settings.
        /// </summary>
        internal static string my_settings {
            get {
                return ResourceManager.GetString("my settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Negotiated.
        /// </summary>
        internal static string negotiated {
            get {
                return ResourceManager.GetString("negotiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No Favorite Ads.
        /// </summary>
        internal static string no_Favorite_Ads {
            get {
                return ResourceManager.GetString("no Favorite Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Online.
        /// </summary>
        internal static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Options.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone number:.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phone number.
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Placement in the top for 7 days.
        /// </summary>
        internal static string Placement_in_the_top_for_7_days {
            get {
                return ResourceManager.GetString("Placement in the top for 7 days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Post an ad.
        /// </summary>
        internal static string post_add {
            get {
                return ResourceManager.GetString("post add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PREMIUM.
        /// </summary>
        internal static string PREMIUM {
            get {
                return ResourceManager.GetString("PREMIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Publish.
        /// </summary>
        internal static string publish {
            get {
                return ResourceManager.GetString("publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Raise for 0.9 €.
        /// </summary>
        internal static string raise {
            get {
                return ResourceManager.GetString("raise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Received.
        /// </summary>
        internal static string received {
            get {
                return ResourceManager.GetString("received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration.
        /// </summary>
        internal static string registr {
            get {
                return ResourceManager.GetString("registr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        internal static string repeat_pass {
            get {
                return ResourceManager.GetString("repeat pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent.
        /// </summary>
        internal static string sent {
            get {
                return ResourceManager.GetString("sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на service, as well as with the transfer and processing of my personal data in ZEGOGO. I confirm my age and responsibility for posting ads.
        /// </summary>
        internal static string service__as {
            get {
                return ResourceManager.GetString("service, as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SIMILAR ANNOUNCEMENTS.
        /// </summary>
        internal static string similar_adv {
            get {
                return ResourceManager.GetString("similar adv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STANDARD.
        /// </summary>
        internal static string STANDARD {
            get {
                return ResourceManager.GetString("STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TARIFFS OF AVAILABLE PAID PACKAGES.
        /// </summary>
        internal static string Tariffs_of_available_paid_packages {
            get {
                return ResourceManager.GetString("Tariffs of available paid packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terms of use / privacy policy and personal data processing.
        /// </summary>
        internal static string terms_of_use {
            get {
                return ResourceManager.GetString("terms of use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на terms of use .
        /// </summary>
        internal static string terms_of_use_space {
            get {
                return ResourceManager.GetString("terms of use space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To advertise.
        /// </summary>
        internal static string to_advertise {
            get {
                return ResourceManager.GetString("to advertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To pay.
        /// </summary>
        internal static string To_pay {
            get {
                return ResourceManager.GetString("To pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top 3 days ad.
        /// </summary>
        internal static string Top_3_days_ad {
            get {
                return ResourceManager.GetString("Top 3 days ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top 30 days ad.
        /// </summary>
        internal static string Top_30_days_ad {
            get {
                return ResourceManager.GetString("Top 30 days ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top 7 days ad.
        /// </summary>
        internal static string Top_7_days_ad {
            get {
                return ResourceManager.GetString("Top 7 days ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 ups.
        /// </summary>
        internal static string ups_5 {
            get {
                return ResourceManager.GetString("ups 5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9 ups.
        /// </summary>
        internal static string ups_9 {
            get {
                return ResourceManager.GetString("ups 9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User did not provide a phone number.
        /// </summary>
        internal static string user_did_not_provide {
            get {
                return ResourceManager.GetString("user did not provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By default, ads on ZEGOGO are displayed by the date they were posted. Using the «7-day Rise» service, your ad will again rise to the top positions in the list every 24 hours, as if you had placed it a moment ago!.
        /// </summary>
        internal static string Using_the_7_day_Rise_service {
            get {
                return ResourceManager.GetString("Using the 7 day Rise service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Views:.
        /// </summary>
        internal static string views {
            get {
                return ResourceManager.GetString("views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Want to place an ad in the most viewed position and get the most feedback? Then the «VIP announcement» is what you need. Your ad will be placed on the ZEGOGO homepage, where everyone will see it!.
        /// </summary>
        internal static string Want_to_place_an_ad_in_the_most_viewed {
            get {
                return ResourceManager.GetString("Want to place an ad in the most viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To write a message....
        /// </summary>
        internal static string write_mess {
            get {
                return ResourceManager.GetString("write mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Write SMS.
        /// </summary>
        internal static string write_sms {
            get {
                return ResourceManager.GetString("write sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong login or password.
        /// </summary>
        internal static string wrong_login_or_password {
            get {
                return ResourceManager.GetString("wrong login or password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can add to favorites from the announcement page or from the announcement list page.
        /// </summary>
        internal static string you_can_add_to_favorites {
            get {
                return ResourceManager.GetString("you can add to favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can also choose additional services for packages to promote your ad and receive feedback.
        /// </summary>
        internal static string You_can_also_choose {
            get {
                return ResourceManager.GetString("You can also choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Zegogo.com team has prepared several affordable paid packages to promote your ads. You can promote your services and products in the category you need, as well as increase the conversion of requests using packages such as: Standard, Business, Premium!
        ///Best regards, Zegogo.com team - New level advertising service!.
        /// </summary>
        internal static string You_can_promote {
            get {
                return ResourceManager.GetString("You can promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your ad is placed in a separate TOP list by category. A great option if you have exactly decided on the category of your ad and you do not need to place a VIP ad..
        /// </summary>
        internal static string Your_ad_is_placed_in_a_separate_TOP_list_by_category_ {
            get {
                return ResourceManager.GetString("Your ad is placed in a separate TOP list by category.", resourceCulture);
            }
        }
    }
}
